USE [master]
GO

/****** Object:  Database [PayrollDatabase]    Script Date: 2018-12-21 3:51:25 PM ******/
CREATE DATABASE [PayrollDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PayrollDatabase', FILENAME = N'D:\Microsoft SQL Server\Data\PayrollDatabase.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PayrollDatabase_log', FILENAME = N'D:\Microsoft SQL Server\Data\PayrollDatabase_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PayrollDatabase] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PayrollDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PayrollDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PayrollDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PayrollDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PayrollDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PayrollDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [PayrollDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PayrollDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PayrollDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PayrollDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PayrollDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PayrollDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PayrollDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PayrollDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PayrollDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PayrollDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PayrollDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PayrollDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PayrollDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PayrollDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PayrollDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PayrollDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PayrollDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PayrollDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [PayrollDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [PayrollDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PayrollDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PayrollDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PayrollDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PayrollDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PayrollDatabase] SET  READ_WRITE 
GO


USE [PayrollDatabase]
GO

/****** Object:  Table [dbo].[JobGroup]    Script Date: 2018-12-21 3:52:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[JobGroup](
	[JobGroupId] [int] IDENTITY(1,1) NOT NULL,
	[Code] [varchar](50) NULL,
	[Rate] [decimal](18, 2) NULL,
 CONSTRAINT [PK_JobGroup] PRIMARY KEY CLUSTERED 
(
	[JobGroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [PayrollDatabase]
GO

/****** Object:  Table [dbo].[TimeKeeping]    Script Date: 2018-12-21 3:53:01 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TimeKeeping](
	[TimeKeepingId] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeId] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[HoursWorked] [float] NOT NULL,
	[JobGroup] [int] NOT NULL,
	[ReportId] [int] NULL,
 CONSTRAINT [PK_TimeKeeping] PRIMARY KEY CLUSTERED 
(
	[TimeKeepingId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


